use_frameworks!

target 'TPFDebugTool_Example' do
  
  pod 'TPFDebugTool', :path => '../'
  pod 'AFNetworking'
  pod 'Reveal-SDK','24'

  post_install do |installer|
       installer.pods_project.build_configurations.each do |config|
         config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
       end
  end
  
end
